branch-defaults:
  default:
    environment: peprally-push
    group_suffix: null
global:
  application_name: peprally-env
  default_ec2_keyname: jervis_ub_keypair
  default_platform: python2.7
  default_region: us-west-2
  profile: null
  sc: null
